# Intro to NumPy

Hello and welcome to your NumPy primer as part of NCI's Parallel Python data science course.

This notebook is designed to cover the fundamentals of `NumPy` very briefly to give you a basis to use it as part of our `Parallel Python` course

The NumPy project has extensive and well explained documentation at the NumPy [homepage](https://numpy.org/). 


## Intro

What is NumPy? To take the simplest explanation, NumPy is the most fundamental package for numerical computing in Python. 
It provides a key functionality that Python lacks, array computing! I'll explain what I mean by array computing later. 

NumPy provides the basic building blocks for the numerical aspects of the PyData stack and is the underlying data representation in a whole host of packages (Think Pandas, Dask, ....)

Alright, lets jump in! 

#### Adding two vectors **without** NumPy

We are going to first explore what the world would look like without NumPy by trying to add two vectors of integers together. 

In vector notation this could be written as:

$A + B = X$

where A, B and X are vectors

To do this in pure python we would use two lists:

In [ ]:
# create our two vectors
A = [0,1,2,3,4,5,6,7,8,9,10,11]
B = [10,11,12,13,14,15,16,17,18,19,20,21]

In [ ]:
# lets loop over it using a numerical index and a for loop

# check the vectors are the same length
assert(len(A) == len(B))
n_elem = len(A)
X = []
for i in range(n_elem):
    X.append(A[i] + B[i])
    
X 

Okay this worked but it did seem a little verbose and clunky. If we were going to do things this way we might as well use a compiled language.

It is also a little bit slow when our lists get bigger. Lets do some basic timings for a 100k element list

In [3]:
# construct our lists
N = 100000
A = []
B = []
for i in range(N):
    A.append(i)
    B.append(i)

Now lets time adding them together using the `%%timeit` Jupyter cell magic which does several runs of the cell and measures its execution time. Very handy!

In [4]:
%%timeit
X = []
for i in range(N):
    X.append(A[i] + B[i])

18.2 ms ± 887 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


On my laptop this took ~ 17 ms give or take. This may sound fast but this operation is very common and can be orders of magnitude faster in compiled languages like C or Fortran. 

**We can do better**


### Adding two vectors with NumPy

Numpy is primarily library for doing array computing among other things. The wikipedia definition of array computing is :

"In computer science, array programming refers to solutions which allow the application of operations to an entire set of values at once. Such solutions are commonly used in scientific and engineering settings."

What does this mean for us?

We can do away with the loops over the number of elements and add our two vectors together directly. Lets see this in action.

In [5]:
# import numpy
import numpy as np

First lets make arrays out of the 100K element lists we used before.

In [6]:
A_numpy = np.array(A)
B_numpy = np.array(B)
A_numpy

array([    0,     1,     2, ..., 99997, 99998, 99999])

We will go more into the attributes of arrays later, but arrays have a handy attribute called `shape`

In [7]:
A_numpy.shape

(100000,)

We can see the array has a `shape` of 100000 in the first dimension

Now lets add our arrays together using array computing !!

In [8]:
X_numpy = A_numpy + B_numpy

Wow that was a lot easier than our janky for loop but is it faster?

In [9]:
%%timeit

X_numpy = A_numpy + B_numpy

71.6 µs ± 7.92 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


On my laptop this is ~ 300x faster!!!

But how? To cut a long story short, the numerically  intensive routines in NumPy  are written in C/C++ (sometimes Cython) giving us the speed of a compiled language with the ease of writing Python.

### Challenge

Multiply the vectors A and B to form array C using  NumPy

In [47]:
# compute C = A*B

<details><summary><b>Solution</b></summary>
   <pre>
    <br> C_numpy = A_numpy* B_numpy
   </pre>
</details>

What else can array computation with NumPy give us?

There are also vectorised (a word used to described vector style operations) implementations of many special functions. For example



In [48]:
sin_B = np.sin(B_numpy)
sin_B

array([0.        , 0.84147098, 0.90929743, ..., 0.10563876, 0.89383946,
       0.86024828])

In [50]:
mean_A = np.mean(A_numpy)
mean_A

49999.5

### Slicing and  multi-dimensional arrays

Arrays can be sliced just like a list using `start:stop:step` notation

In [11]:
# construct a range of values using arange
r = np.arange(20)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
# grab every element 
r[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
# grab the first ten elements
r[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# grab the 10th to 15th elements 
r[10:15]

array([10, 11, 12, 13, 14])

In [15]:
# grab the last 10 elements 
r[-10:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
# grab every second element 
r[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Arrays can have multiple dimensions! this is the real power of NumPy as you will hopefully see in the Parallel python course.

In [17]:
# make a range and then reshape it to by a two dimensional array
N = 20
two_dimensional = np.arange(3*N).reshape(N,3)
two_dimensional

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [18]:
two_dimensional.shape

(20, 3)

We can see that our array is two dimensional with shape `20,3`. Slicing works similarly for multidimensional arrays with the indicies ordered row, column


In [22]:
# slice to get a row  
two_dimensional[0,:]


array([0, 1, 2])

In [24]:
#slice to get a column
two_dimensional[:,1]


array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58])

In [27]:
# slice to get an individual value  (the first one)
two_dimensional[0,0]

0

### Using NumPy functions on multidimensional arrays

If you only wish to compute a function or property on a single dimension you can provide an axis using the `axis=X` keyword.

In [55]:
# mean in both dimensions

np.mean(two_dimensional)

29.5

In [53]:
#mean in the first dimension
np.mean(two_dimensional, axis=0)

array([28.5, 29.5, 30.5])

In [57]:
# mean in the second dimension
np.mean(two_dimensional, axis=1)

array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25., 28., 31., 34., 37.,
       40., 43., 46., 49., 52., 55., 58.])

### More complicated operations

NumPy also supports arbitrary linear algebra operations.
The full scope of these is beyond this course, but just as an example lets compute the square of the matrix $Z$

\begin{matrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{matrix}


$Z^2 = ZZ$


In [62]:
Z = np.arange(9).reshape(3,3)

z_squared = np.matmul(Z, Z)
z_squared

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

The same can be achieved using the matmul operator `@`

In [65]:
z_squared = Z@Z
z_squared

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

### More than two dimensions

We can make arrays up to 32 dimensions. Lets make two 3D tensors X and Y and find their tensor product $ X \otimes Y$

In [36]:
N = 20
X = np.arange(N*3*3).reshape(N,3,3)
Y = np.arange(N*3*3).reshape(N,3,3)
X.shape


(20, 3, 3)

In [45]:
res = np.tensordot(X, Y, axes=0)


In [46]:
res.shape

(20, 3, 3, 20, 3, 3)

### Summary

The maths we have done here is not really important. In fact I am terrible at linear algebra myself.

What is important is that you can see the immense power of array computation using numpy and have a feel for how to work with arrays rather than lists or individual numbers. 

The power of NumPy is incredible and I guarantee that if you have a numerical  problem it can be made simpler with NumPy!

Hopefully this has given you just a small taste of what you can do with numpy and helps you out with the rest of the course. 